name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          
      - name: Build for Cloudflare
        run: CLOUDFLARE_BUILD=true pnpm exec opennextjs-cloudflare build
        env:
          NEXT_PUBLIC_REPO: ${{ secrets.NEXT_PUBLIC_REPO }}
          NEXT_PUBLIC_REPO_ID: ${{ secrets.NEXT_PUBLIC_REPO_ID }}
          NEXT_PUBLIC_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_CATEGORY_ID }}
          UMAMI_ID: ${{ secrets.UMAMI_ID }}
          UMAMI_URL: ${{ secrets.UMAMI_URL }}
      
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}