name: YehezGun CI

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install Deps (frozen)
        run: pnpm install --frozen-lockfile
      - name: Run Biome
        run: pnpm biome:lint:ci
      - name: Build
        run: pnpm build
      - name: Build For Cloudflare Workers
        run: pnpm cloudflare:build:ci
        env:
          NEXT_PUBLIC_REPO: ${{ secrets.NEXT_PUBLIC_REPO }}
          NEXT_PUBLIC_REPO_ID: ${{ secrets.NEXT_PUBLIC_REPO_ID }}
          NEXT_PUBLIC_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_CATEGORY_ID }}
          NEXT_PUBLIC_UMAMI_URL: ${{ secrets.NEXT_PUBLIC_UMAMI_URL }}
          NEXT_PUBLIC_UMAMI_ID: ${{ secrets.NEXT_PUBLIC_UMAMI_ID }}
      - name: Unit Testing & Coverage
        run: pnpm test:coverage
